In [1]:
# 🏠 Property Search & Filter Engine

## Mumbai House Price Prediction Project

This notebook creates an interactive-style property search and filtering system.

### Features:
- Locality filter
- Price range filter
- Area range filter
- Bedroom filter
- Bathroom filter
- Property type filter
- Furnishing filter
- Price per sq.ft. filter
- Deal status filter
- Anomaly filter
- Search result ranking
- Export filtered properties to CSV

### Objective:
Build a practical property search engine using the processed
property intelligence dataset.

SyntaxError: invalid syntax (1378053000.py, line 5)

In [2]:
## Notebook Objectives

By the end of this notebook we will:

1. Load the property intelligence dataset
2. Validate required columns
3. Understand available property filters
4. Create a reusable property filtering function
5. Apply individual filters
6. Apply multiple filters together
7. Rank matching properties
8. Identify attractive properties
9. Export search results
10. Create a final reusable search function

SyntaxError: invalid syntax (144254726.py, line 3)

In [3]:
import os
import numpy as np
import pandas as pd

from IPython.display import display

print("Libraries imported successfully!")

Libraries imported successfully!

In [4]:
PROJECT_DIR = r"C:\Users\Tejas Dalvi\OneDrive\Documents\mumbai-house-price-prediction"

OUTPUT_DIR = os.path.join(
    PROJECT_DIR,
    "outputs"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

print("Project Directory:")
print(PROJECT_DIR)

print()

print("Output Directory:")
print(OUTPUT_DIR)

Project Directory:
C:\Users\Tejas Dalvi\OneDrive\Documents\mumbai-house-price-prediction

Output Directory:
C:\Users\Tejas Dalvi\OneDrive\Documents\mumbai-house-price-prediction\outputs

In [5]:
print("Searching for property_intelligence.csv...")
print()

found_files = []

for root, dirs, files in os.walk(PROJECT_DIR):
    for file in files:
        if file.lower() == "property_intelligence.csv":
            found_files.append(
                os.path.join(root, file)
            )

if len(found_files) == 0:

    print("❌ property_intelligence.csv was NOT found.")

else:

    print("✅ File found!")

    for i, file_path in enumerate(found_files):
        print(f"{i + 1}. {file_path}")

    property_path = found_files[0]

    print()
    print("Selected file:")
    print(property_path)

Searching for property_intelligence.csv...

✅ File found!
1. C:\Users\Tejas Dalvi\OneDrive\Documents\mumbai-house-price-prediction\data\processed\property_intelligence.csv

Selected file:
C:\Users\Tejas Dalvi\OneDrive\Documents\mumbai-house-price-prediction\data\processed\property_intelligence.csv

In [6]:
df = pd.read_csv(
    property_path
)

print("Dataset loaded successfully!")

print()
print("Shape:", df.shape)

print()
print("Columns:")
print(df.columns.tolist())

Dataset loaded successfully!

Shape: (51767, 22)

Columns:
['price', 'area', 'price_per_sqft', 'locality', 'city', 'property_type', 'bedroom_num', 'bathroom_num', 'balcony_num', 'furnished', 'age', 'total_floors', 'latitude', 'longitude', 'predicted_price', 'price_difference', 'price_difference_percent', 'predicted_price_per_sqft', 'price_per_sqft_difference', 'anomaly_label', 'anomaly_score', 'is_anomaly']

In [7]:
display(
    df.head(10)
)

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,6600283,757,8719.000000,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.244410,73.123253,5.749573e+06,8.507096e+05,14.796047,7595.209299,1123.790701,1,0.261409,False
1,6169841,652,9462.946319,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,6.422073e+06,-2.522321e+05,-3.927581,9849.805444,-386.859125,1,0.257219,False
2,4599936,396,11616.000000,Dombivali,Mumbai,Apartment,1,1,0,Unfurnished,...,19.209026,73.081276,4.378319e+06,2.216174e+05,5.061702,11056.360025,559.639975,1,0.242774,False
3,51980000,1130,46000.000000,Ville Parle,Mumbai,Apartment,3,3,0,Unfurnished,...,19.097841,72.851158,5.084753e+07,1.132471e+06,2.227190,44997.813310,1002.186690,1,0.214435,False
4,3915000,435,9000.000000,Nala Sopara,Mumbai,Apartment,1,1,0,Unfurnished,...,19.420601,72.809319,3.663747e+06,2.512535e+05,6.857829,8422.405793,577.594207,1,0.208075,False
5,4900320,720,6806.000000,Ulwe,Mumbai,Apartment,1,1,0,Unfurnished,...,18.967562,73.024956,4.995038e+06,-9.471752e+04,-1.896232,6937.552112,-131.552112,1,0.235139,False
6,14000000,652,21472.392638,Jogeshwari,Mumbai,Apartment,2,2,0,Unfurnished,...,19.137762,72.860130,1.542673e+07,-1.426730e+06,-9.248425,23660.628201,-2188.235563,1,0.290705,False
7,16400255,565,29027.000000,Chembur,Mumbai,Apartment,2,2,0,Unfurnished,...,19.032211,72.895226,1.715704e+07,-7.567897e+05,-4.410956,30366.450756,-1339.450756,1,0.269804,False
8,74998440,1770,42372.000000,Nerul,Mumbai,Apartment,3,3,0,Unfurnished,...,19.008259,73.013031,6.986062e+07,5.137817e+06,7.354382,39469.278617,2902.721383,1,0.154434,False
9,65900000,2600,25346.153846,Mulund,Mumbai,Apartment,4,5,0,Unfurnished,...,19.184473,72.940758,6.111737e+07,4.782634e+06,7.825328,23506.679101,1839.474745,1,0.082781,False

In [8]:
print("Dataset Information")
print("=" * 70)

print("Rows:", len(df))
print("Columns:", len(df.columns))

print()
print("Data Types:")

display(
    df.dtypes.to_frame("Data Type")
)

Dataset Information
======================================================================
Rows: 51767
Columns: 22

Data Types:

                          Data Type
price                         int64
area                          int64
price_per_sqft              float64
locality                        str
city                            str
property_type                   str
bedroom_num                   int64
bathroom_num                  int64
balcony_num                   int64
furnished                       str
age                           int64
total_floors                  int64
latitude                    float64
longitude                   float64
predicted_price             float64
price_difference            float64
price_difference_percent    float64
predicted_price_per_sqft    float64
price_per_sqft_difference   float64
anomaly_label                 int64
anomaly_score               float64
is_anomaly                     bool

In [9]:
required_columns = [
    "locality",
    "price",
    "area",
    "price_per_sqft",
    "predicted_price",
    "predicted_price_per_sqft",
    "property_type",
    "bedroom_num",
    "bathroom_num",
    "furnished",
    "anomaly_label",
    "anomaly_score",
    "is_anomaly"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if len(missing_columns) == 0:

    print("✅ All required columns are available.")

else:

    print("❌ Missing columns:")
    print(missing_columns)

✅ All required columns are available.

In [10]:
numeric_columns = [
    "price",
    "area",
    "price_per_sqft",
    "predicted_price",
    "predicted_price_per_sqft",
    "bedroom_num",
    "bathroom_num",
    "anomaly_score"
]

for col in numeric_columns:

    if col in df.columns:

        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )

print("Numeric columns converted successfully.")

Numeric columns converted successfully.

In [11]:
search_df = df.copy()

search_df = search_df.dropna(
    subset=[
        "locality",
        "price",
        "area"
    ]
)

search_df = search_df[
    (search_df["price"] > 0) &
    (search_df["area"] > 0)
].copy()

search_df.reset_index(
    drop=True,
    inplace=True
)

print("Search dataset prepared successfully.")

print()
print("Original rows:", len(df))
print("Searchable rows:", len(search_df))

Search dataset prepared successfully.

Original rows: 51767
Searchable rows: 51767

In [12]:
localities = sorted(
    search_df["locality"]
    .dropna()
    .astype(str)
    .unique()
)

print("Total Localities:", len(localities))

print()
print("First 30 Localities:")

for locality in localities[:30]:
    print("-", locality)

Total Localities: 408

First 30 Localities:
- Acc Cement Road
- Adarsh Nagar
- Additional M.I.D.C
- Adharwadi
- Agasan Village
- Agripada
- Airoli
- Altamount Road
- Ambarnath
- Ambernath
- Ambivali
- Ambivli
- Amboli
- Anand Nagar
- Anand Nagar,Dahisar
- Andheri
- Anjurdive
- Antarli
- Antop Hill
- Anushakti Nagar
- Arya Nagar
- Asalpha
- Asangaon
- Ashok Nagar
- Atgaon
- Babhai
- Badlapur
- Balkum
- Bandra
- Bandra Kurla Complex

In [13]:
property_types = sorted(
    search_df["property_type"]
    .dropna()
    .astype(str)
    .unique()
)

print("Available Property Types:")

for property_type in property_types:
    print("-", property_type)

Available Property Types:
- Apartment
- Independent Floor
- Independent House
- Studio Apartment
- Villa

In [14]:
furnishing_options = sorted(
    search_df["furnished"]
    .dropna()
    .astype(str)
    .unique()
)

print("Available Furnishing Options:")

for option in furnishing_options:
    print("-", option)

Available Furnishing Options:
- Furnished
- Semi-Furnished
- Unfurnished

In [15]:
bedroom_options = sorted(
    search_df["bedroom_num"]
    .dropna()
    .unique()
)

print("Available Bedroom Counts:")

print(
    bedroom_options
)

Available Bedroom Counts:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(12), np.int64(15)]

In [16]:
bathroom_options = sorted(
    search_df["bathroom_num"]
    .dropna()
    .unique()
)

print("Available Bathroom Counts:")

print(
    bathroom_options
)

Available Bathroom Counts:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(12), np.int64(15)]

In [17]:
print("PROPERTY PRICE RANGE")
print("=" * 60)

print(
    f"Minimum Price: ₹{search_df['price'].min():,.0f}"
)

print(
    f"Maximum Price: ₹{search_df['price'].max():,.0f}"
)

print(
    f"Median Price: ₹{search_df['price'].median():,.0f}"
)

PROPERTY PRICE RANGE
============================================================
Minimum Price: ₹32,000
Maximum Price: ₹2,147,483,647
Median Price: ₹12,000,000

In [18]:
print("PROPERTY AREA RANGE")
print("=" * 60)

print(
    f"Minimum Area: {search_df['area'].min():,.0f} sq.ft."
)

print(
    f"Maximum Area: {search_df['area'].max():,.0f} sq.ft."
)

print(
    f"Median Area: {search_df['area'].median():,.0f} sq.ft."
)

PROPERTY AREA RANGE
============================================================
Minimum Area: 123 sq.ft.
Maximum Area: 24,109 sq.ft.
Median Area: 804 sq.ft.

In [19]:
print("PRICE PER SQ.FT RANGE")
print("=" * 60)

print(
    f"Minimum: ₹{search_df['price_per_sqft'].min():,.0f}"
)

print(
    f"Maximum: ₹{search_df['price_per_sqft'].max():,.0f}"
)

print(
    f"Median: ₹{search_df['price_per_sqft'].median():,.0f}"
)

PRICE PER SQ.FT RANGE
============================================================
Minimum: ₹25
Maximum: ₹290,000
Median: ₹15,642

In [20]:
# 🔎 Property Filtering Engine

The following function allows multiple filters to be applied simultaneously.

Available filters:

- Locality
- Minimum price
- Maximum price
- Minimum area
- Maximum area
- Bedrooms
- Bathrooms
- Property type
- Furnishing
- Minimum price/sq.ft.
- Maximum price/sq.ft.
- Deal status
- Anomaly status

SyntaxError: invalid syntax (1126980291.py, line 3)

In [21]:
def search_properties(
    data,
    locality=None,
    min_price=None,
    max_price=None,
    min_area=None,
    max_area=None,
    bedrooms=None,
    bathrooms=None,
    property_type=None,
    furnished=None,
    min_ppsf=None,
    max_ppsf=None,
    deal_status=None,
    anomaly_status=None
):

    result = data.copy()

    # Locality
    if locality is not None:

        if locality != "All":

            result = result[
                result["locality"].astype(str).str.lower()
                == str(locality).lower()
            ]

    # Price
    if min_price is not None:

        result = result[
            result["price"] >= min_price
        ]

    if max_price is not None:

        result = result[
            result["price"] <= max_price
        ]

    # Area
    if min_area is not None:

        result = result[
            result["area"] >= min_area
        ]

    if max_area is not None:

        result = result[
            result["area"] <= max_area
        ]

    # Bedrooms
    if bedrooms is not None:

        result = result[
            result["bedroom_num"] == bedrooms
        ]

    # Bathrooms
    if bathrooms is not None:

        result = result[
            result["bathroom_num"] == bathrooms
        ]

    # Property type
    if property_type is not None:

        if property_type != "All":

            result = result[
                result["property_type"].astype(str).str.lower()
                == str(property_type).lower()
            ]

    # Furnishing
    if furnished is not None:

        if furnished != "All":

            result = result[
                result["furnished"].astype(str).str.lower()
                == str(furnished).lower()
            ]

    # Price per sq.ft.
    if min_ppsf is not None:

        result = result[
            result["price_per_sqft"] >= min_ppsf
        ]

    if max_ppsf is not None:

        result = result[
            result["price_per_sqft"] <= max_ppsf
        ]

    # Deal status
    if deal_status is not None:

        if "deal_status" in result.columns:

            result = result[
                result["deal_status"].astype(str).str.lower()
                == str(deal_status).lower()
            ]

    # Anomaly status
    if anomaly_status is not None:

        if anomaly_status == "Normal":

            result = result[
                result["is_anomaly"] == False
            ]

        elif anomaly_status == "Anomaly":

            result = result[
                result["is_anomaly"] == True
            ]

    result = result.reset_index(
        drop=True
    )

    return result


print("✅ Property search function created successfully!")

✅ Property search function created successfully!

In [22]:
if len(localities) > 0:

    test_locality = localities[0]

    locality_results = search_properties(
        search_df,
        locality=test_locality
    )

    print(
        "Search Locality:",
        test_locality
    )

    print(
        "Matching Properties:",
        len(locality_results)
    )

    display(
        locality_results.head(10)
    )

Search Locality: Acc Cement Road
Matching Properties: 1

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,10000000,665,15037.593985,Acc Cement Road,Mumbai,Apartment,1,2,1,Unfurnished,...,19.180456,72.95842,9.380265e+06,619735.017733,6.606796,14105.661627,931.932357,1,0.186752,False

In [23]:
price_results = search_properties(
    search_df,
    min_price=5_000_000,
    max_price=15_000_000
)

print("Price Range:")
print("₹50 Lakhs - ₹1.5 Crore")

print()
print(
    "Matching Properties:",
    len(price_results)
)

display(
    price_results.head(10)
)

Price Range:
₹50 Lakhs - ₹1.5 Crore

Matching Properties: 22470

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,6600283,757,8719.000000,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.244410,73.123253,5.749573e+06,8.507096e+05,14.796047,7595.209299,1123.790701,1,0.261409,False
1,6169841,652,9462.946319,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,6.422073e+06,-2.522321e+05,-3.927581,9849.805444,-386.859125,1,0.257219,False
2,14000000,652,21472.392638,Jogeshwari,Mumbai,Apartment,2,2,0,Unfurnished,...,19.137762,72.860130,1.542673e+07,-1.426730e+06,-9.248425,23660.628201,-2188.235563,1,0.290705,False
3,7564352,801,9443.635456,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,7.183914e+06,3.804382e+05,5.295696,8968.681344,474.954112,1,0.256649,False
4,7600395,1095,6941.000000,Ulwe,Mumbai,Apartment,2,2,0,Unfurnished,...,18.967562,73.024956,8.113010e+06,-5.126148e+05,-6.318430,7409.141407,-468.141407,1,0.251978,False
5,9900000,463,21382.289417,Jogeshwari,Mumbai,Apartment,1,1,0,Unfurnished,...,19.137762,72.860130,1.019959e+07,-2.995917e+05,-2.937291,22029.355724,-647.066307,1,0.253829,False
6,12001385,415,28919.000000,Chembur,Mumbai,Apartment,1,1,0,Unfurnished,...,19.032211,72.895226,1.148116e+07,5.202247e+05,4.531116,27665.446574,1253.553426,1,0.226398,False
7,6200000,685,9051.094891,Taloje,Mumbai,Apartment,1,1,0,Unfurnished,...,19.074299,73.116592,5.138276e+06,1.061724e+06,20.663033,7501.133265,1549.961625,1,0.227223,False
8,5500000,350,15714.285714,Kharghar,Mumbai,Apartment,1,1,0,Unfurnished,...,19.063528,73.057495,5.545415e+06,-4.541461e+04,-0.818958,15844.041730,-129.756016,1,0.236761,False
9,11000000,1000,11000.000000,Koper Khairane,Mumbai,Apartment,2,2,0,Unfurnished,...,19.101860,73.008682,1.182966e+07,-8.296558e+05,-7.013355,11829.655755,-829.655755,1,0.281111,False

In [24]:
area_results = search_properties(
    search_df,
    min_area=500,
    max_area=1500
)

print("Area Range:")
print("500 - 1500 sq.ft.")

print()
print(
    "Matching Properties:",
    len(area_results)
)

display(
    area_results.head(10)
)

Area Range:
500 - 1500 sq.ft.

Matching Properties: 39395

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,6600283,757,8719.000000,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.244410,73.123253,5.749573e+06,8.507096e+05,14.796047,7595.209299,1123.790701,1,0.261409,False
1,6169841,652,9462.946319,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,6.422073e+06,-2.522321e+05,-3.927581,9849.805444,-386.859125,1,0.257219,False
2,51980000,1130,46000.000000,Ville Parle,Mumbai,Apartment,3,3,0,Unfurnished,...,19.097841,72.851158,5.084753e+07,1.132471e+06,2.227190,44997.813310,1002.186690,1,0.214435,False
3,4900320,720,6806.000000,Ulwe,Mumbai,Apartment,1,1,0,Unfurnished,...,18.967562,73.024956,4.995038e+06,-9.471752e+04,-1.896232,6937.552112,-131.552112,1,0.235139,False
4,14000000,652,21472.392638,Jogeshwari,Mumbai,Apartment,2,2,0,Unfurnished,...,19.137762,72.860130,1.542673e+07,-1.426730e+06,-9.248425,23660.628201,-2188.235563,1,0.290705,False
5,16400255,565,29027.000000,Chembur,Mumbai,Apartment,2,2,0,Unfurnished,...,19.032211,72.895226,1.715704e+07,-7.567897e+05,-4.410956,30366.450756,-1339.450756,1,0.269804,False
6,3000000,590,5084.745763,Nallasopara W,Mumbai,Apartment,1,1,0,Unfurnished,...,19.417505,72.817940,3.267132e+06,-2.671325e+05,-8.176359,5537.512686,-452.766923,1,0.202036,False
7,7564352,801,9443.635456,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,7.183914e+06,3.804382e+05,5.295696,8968.681344,474.954112,1,0.256649,False
8,41007620,891,46024.264871,Ville Parle,Mumbai,Apartment,3,3,0,Unfurnished,...,19.097841,72.851158,3.998547e+07,1.022145e+06,2.556291,44877.076263,1147.188608,1,0.216173,False
9,7600395,1095,6941.000000,Ulwe,Mumbai,Apartment,2,2,0,Unfurnished,...,18.967562,73.024956,8.113010e+06,-5.126148e+05,-6.318430,7409.141407,-468.141407,1,0.251978,False

In [25]:
bedroom_results = search_properties(
    search_df,
    bedrooms=2
)

print("Bedroom Filter: 2 BHK")

print()
print(
    "Matching Properties:",
    len(bedroom_results)
)

display(
    bedroom_results.head(10)
)

Bedroom Filter: 2 BHK

Matching Properties: 21682

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,6600283,757,8719.000000,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.244410,73.123253,5.749573e+06,8.507096e+05,14.796047,7595.209299,1123.790701,1,0.261409,False
1,6169841,652,9462.946319,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,6.422073e+06,-2.522321e+05,-3.927581,9849.805444,-386.859125,1,0.257219,False
2,14000000,652,21472.392638,Jogeshwari,Mumbai,Apartment,2,2,0,Unfurnished,...,19.137762,72.860130,1.542673e+07,-1.426730e+06,-9.248425,23660.628201,-2188.235563,1,0.290705,False
3,16400255,565,29027.000000,Chembur,Mumbai,Apartment,2,2,0,Unfurnished,...,19.032211,72.895226,1.715704e+07,-7.567897e+05,-4.410956,30366.450756,-1339.450756,1,0.269804,False
4,7564352,801,9443.635456,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,7.183914e+06,3.804382e+05,5.295696,8968.681344,474.954112,1,0.256649,False
5,7600395,1095,6941.000000,Ulwe,Mumbai,Apartment,2,2,0,Unfurnished,...,18.967562,73.024956,8.113010e+06,-5.126148e+05,-6.318430,7409.141407,-468.141407,1,0.251978,False
6,4000000,550,7272.727273,Dombivali,Mumbai,Apartment,2,2,0,Unfurnished,...,19.201017,73.094048,4.513101e+06,-5.131014e+05,-11.369152,8205.638833,-932.911560,1,0.223180,False
7,11000000,1000,11000.000000,Koper Khairane,Mumbai,Apartment,2,2,0,Unfurnished,...,19.101860,73.008682,1.182966e+07,-8.296558e+05,-7.013355,11829.655755,-829.655755,1,0.281111,False
8,11500000,1330,8646.616541,Kalamboli,Mumbai,Apartment,2,2,0,Semi-Furnished,...,19.037115,73.088913,1.153400e+07,-3.400000e+04,-0.294781,8672.180451,-25.563910,1,0.217529,False
9,10800000,1139,9482.001756,Kalamboli,Mumbai,Apartment,2,2,0,Semi-Furnished,...,19.034883,73.093620,9.991903e+06,8.080971e+05,8.087520,8772.522257,709.479499,1,0.239632,False

In [26]:
# 🎯 Multi-Filter Property Search

Now we combine multiple conditions.

Example:

- Price: ₹50 Lakhs – ₹1.5 Crore
- Area: 600 – 1500 sq.ft.
- Bedrooms: 2
- Bathrooms: 2

SyntaxError: invalid character '₹' (U+20B9) (2970915889.py, line 7)

In [27]:
multi_results = search_properties(
    search_df,
    min_price=5_000_000,
    max_price=15_000_000,
    min_area=600,
    max_area=1500,
    bedrooms=2,
    bathrooms=2
)

print("MULTI-FILTER SEARCH")
print("=" * 70)

print(
    "Price: ₹50L - ₹1.5Cr"
)

print(
    "Area: 600 - 1500 sq.ft."
)

print(
    "Bedrooms: 2"
)

print(
    "Bathrooms: 2"
)

print()
print(
    "Matching Properties:",
    len(multi_results)
)

display(
    multi_results.head(20)
)

MULTI-FILTER SEARCH
======================================================================
Price: ₹50L - ₹1.5Cr
Area: 600 - 1500 sq.ft.
Bedrooms: 2
Bathrooms: 2

Matching Properties: 9026

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,6600283,757,8719.000000,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.244410,73.123253,5.749573e+06,8.507096e+05,14.796047,7595.209299,1123.790701,1,0.261409,False
1,6169841,652,9462.946319,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,6.422073e+06,-2.522321e+05,-3.927581,9849.805444,-386.859125,1,0.257219,False
2,14000000,652,21472.392638,Jogeshwari,Mumbai,Apartment,2,2,0,Unfurnished,...,19.137762,72.860130,1.542673e+07,-1.426730e+06,-9.248425,23660.628201,-2188.235563,1,0.290705,False
3,7564352,801,9443.635456,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,7.183914e+06,3.804382e+05,5.295696,8968.681344,474.954112,1,0.256649,False
4,7600395,1095,6941.000000,Ulwe,Mumbai,Apartment,2,2,0,Unfurnished,...,18.967562,73.024956,8.113010e+06,-5.126148e+05,-6.318430,7409.141407,-468.141407,1,0.251978,False
5,11000000,1000,11000.000000,Koper Khairane,Mumbai,Apartment,2,2,0,Unfurnished,...,19.101860,73.008682,1.182966e+07,-8.296558e+05,-7.013355,11829.655755,-829.655755,1,0.281111,False
6,11500000,1330,8646.616541,Kalamboli,Mumbai,Apartment,2,2,0,Semi-Furnished,...,19.037115,73.088913,1.153400e+07,-3.400000e+04,-0.294781,8672.180451,-25.563910,1,0.217529,False
7,10800000,1139,9482.001756,Kalamboli,Mumbai,Apartment,2,2,0,Semi-Furnished,...,19.034883,73.093620,9.991903e+06,8.080971e+05,8.087520,8772.522257,709.479499,1,0.239632,False
8,9090000,951,9558.359621,Kasaradavali Thane,Mumbai,Apartment,2,2,0,Semi-Furnished,...,19.268215,72.973160,8.975489e+06,1.145110e+05,1.275819,9437.948461,120.411160,1,0.260659,False
9,8700000,1124,7740.213523,Kalyan,Mumbai,Apartment,2,2,0,Semi-Furnished,...,19.262091,73.146042,8.694673e+06,5.327263e+03,0.061270,7735.473965,4.739558,1,0.235370,False
10,9200000,1100,8363.636364,Ulwe,Mumbai,Apartment,2,2,0,Unfurnished,...,18.965935,73.021461,1.034581e+07,-1.145815e+06,-11.075151,9405.286009,-1041.649645,1,0.247217,False
11,8500000,900,9444.444444,Kalyan,Mumbai,Apartment,2,2,0,Semi-Furnished,...,19.259438,73.120468,6.695106e+06,1.804894e+06,26.958414,7439.006345,2005.438099,1,0.264165,False
12,10200000,1062,9604.519774,Mira Road,Mumbai,Apartment,2,2,0,Semi-Furnished,...,19.297215,72.871880,9.978140e+06,2.218603e+05,2.223464,9395.611749,208.908025,1,0.277480,False
13,7100000,985,7208.121827,Kalyan,Mumbai,Apartment,2,2,0,Semi-Furnished,...,19.262615,73.145599,7.269091e+06,-1.690911e+05,-2.326166,7379.787952,-171.666124,1,0.226686,False
14,8500000,1000,8500.000000,Taloja,Mumbai,Apartment,2,2,0,Unfurnished,...,19.047300,73.069901,7.198771e+06,1.301229e+06,18.075705,7198.771325,1301.228675,1,0.275722,False
15,9900000,1000,9900.000000,Kharghar,Mumbai,Apartment,2,2,0,Unfurnished,...,19.089449,73.076767,8.400467e+06,1.499533e+06,17.850596,8400.466667,1499.533333,1,0.275690,False
16,10000000,750,13333.333333,Panvel,Mumbai,Apartment,2,2,0,Unfurnished,...,18.936331,73.189865,9.836144e+06,1.638561e+05,1.665857,13114.858560,218.474773,1,0.221691,False
17,11500000,1100,10454.545455,Kharghar,Mumbai,Apartment,2,2,0,Furnished,...,19.063526,73.057495,1.148642e+07,1.357678e+04,0.118199,10442.202923,12.342531,1,0.222426,False
18,11500000,1100,10454.545455,Kharghar,Mumbai,Apartment,2,2,0,Unfurnished,...,19.063526,73.057495,1.119072e+07,3.092769e+05,2.763690,10173.384650,281.160805,1,0.231238,False
19,13000000,1125,11555.555556,Kharghar,Mumbai,Apartment,2,2,0,Unfurnished,...,19.072079,73.079086,1.248533e+07,5.146667e+05,4.122170,11098.074074,457.481481,1,0.272341,False

In [28]:
if len(localities) > 0:

    selected_locality = localities[0]

    locality_budget_results = search_properties(
        search_df,
        locality=selected_locality,
        min_price=5_000_000,
        max_price=20_000_000
    )

    print("LOCALITY + BUDGET SEARCH")
    print("=" * 70)

    print(
        "Locality:",
        selected_locality
    )

    print(
        "Budget: ₹50L - ₹2Cr"
    )

    print()
    print(
        "Matching Properties:",
        len(locality_budget_results)
    )

    display(
        locality_budget_results.head(20)
    )

LOCALITY + BUDGET SEARCH
======================================================================
Locality: Acc Cement Road
Budget: ₹50L - ₹2Cr

Matching Properties: 1

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,10000000,665,15037.593985,Acc Cement Road,Mumbai,Apartment,1,2,1,Unfurnished,...,19.180456,72.95842,9.380265e+06,619735.017733,6.606796,14105.661627,931.932357,1,0.186752,False

In [29]:
if len(property_types) > 0:

    selected_type = property_types[0]

    type_results = search_properties(
        search_df,
        property_type=selected_type
    )

    print("PROPERTY TYPE SEARCH")
    print("=" * 70)

    print(
        "Property Type:",
        selected_type
    )

    print()
    print(
        "Matching Properties:",
        len(type_results)
    )

    display(
        type_results.head(10)
    )

PROPERTY TYPE SEARCH
======================================================================
Property Type: Apartment

Matching Properties: 50960

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,6600283,757,8719.000000,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.244410,73.123253,5.749573e+06,8.507096e+05,14.796047,7595.209299,1123.790701,1,0.261409,False
1,6169841,652,9462.946319,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,6.422073e+06,-2.522321e+05,-3.927581,9849.805444,-386.859125,1,0.257219,False
2,4599936,396,11616.000000,Dombivali,Mumbai,Apartment,1,1,0,Unfurnished,...,19.209026,73.081276,4.378319e+06,2.216174e+05,5.061702,11056.360025,559.639975,1,0.242774,False
3,51980000,1130,46000.000000,Ville Parle,Mumbai,Apartment,3,3,0,Unfurnished,...,19.097841,72.851158,5.084753e+07,1.132471e+06,2.227190,44997.813310,1002.186690,1,0.214435,False
4,3915000,435,9000.000000,Nala Sopara,Mumbai,Apartment,1,1,0,Unfurnished,...,19.420601,72.809319,3.663747e+06,2.512535e+05,6.857829,8422.405793,577.594207,1,0.208075,False
5,4900320,720,6806.000000,Ulwe,Mumbai,Apartment,1,1,0,Unfurnished,...,18.967562,73.024956,4.995038e+06,-9.471752e+04,-1.896232,6937.552112,-131.552112,1,0.235139,False
6,14000000,652,21472.392638,Jogeshwari,Mumbai,Apartment,2,2,0,Unfurnished,...,19.137762,72.860130,1.542673e+07,-1.426730e+06,-9.248425,23660.628201,-2188.235563,1,0.290705,False
7,16400255,565,29027.000000,Chembur,Mumbai,Apartment,2,2,0,Unfurnished,...,19.032211,72.895226,1.715704e+07,-7.567897e+05,-4.410956,30366.450756,-1339.450756,1,0.269804,False
8,74998440,1770,42372.000000,Nerul,Mumbai,Apartment,3,3,0,Unfurnished,...,19.008259,73.013031,6.986062e+07,5.137817e+06,7.354382,39469.278617,2902.721383,1,0.154434,False
9,65900000,2600,25346.153846,Mulund,Mumbai,Apartment,4,5,0,Unfurnished,...,19.184473,72.940758,6.111737e+07,4.782634e+06,7.825328,23506.679101,1839.474745,1,0.082781,False

In [30]:
if len(furnishing_options) > 0:

    selected_furnishing = furnishing_options[0]

    furnishing_results = search_properties(
        search_df,
        furnished=selected_furnishing
    )

    print("FURNISHING SEARCH")
    print("=" * 70)

    print(
        "Furnishing:",
        selected_furnishing
    )

    print()
    print(
        "Matching Properties:",
        len(furnishing_results)
    )

    display(
        furnishing_results.head(10)
    )

FURNISHING SEARCH
======================================================================
Furnishing: Furnished

Matching Properties: 4069

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,3300000,420,7857.142857,Dombivli,Mumbai,Apartment,1,1,0,Furnished,...,19.219631,73.081886,3.253941e+06,4.605853e+04,1.415469,7747.479679,109.663178,1,0.209729,False
1,11500000,1100,10454.545455,Kharghar,Mumbai,Apartment,2,2,0,Furnished,...,19.063526,73.057495,1.148642e+07,1.357678e+04,0.118199,10442.202923,12.342531,1,0.222426,False
2,12400000,950,13052.631579,Thane,Mumbai,Apartment,2,2,0,Furnished,...,19.237597,72.970932,1.247033e+07,-7.033497e+04,-0.564018,13126.668394,-74.036815,1,0.230930,False
3,10500000,1150,9130.434783,Kharghar,Mumbai,Apartment,2,2,0,Furnished,...,19.070892,73.070030,1.074109e+07,-2.410876e+05,-2.244536,9340.076201,-209.641418,1,0.241163,False
4,51500000,2425,21237.113402,Thane,Mumbai,Apartment,4,4,0,Furnished,...,19.260197,72.985138,5.207100e+07,-5.710000e+05,-1.096580,21472.577320,-235.463918,1,0.079170,False
5,5500000,550,10000.000000,Thane,Mumbai,Apartment,1,1,0,Furnished,...,19.260660,72.968460,5.839663e+06,-3.396625e+05,-5.816475,10617.568227,-617.568227,1,0.257034,False
6,18500000,1150,16086.956522,Vashi,Mumbai,Apartment,2,2,0,Furnished,...,19.064241,73.001587,2.019178e+07,-1.691784e+06,-8.378575,17558.072849,-1471.116328,1,0.274561,False
7,19200000,1000,19200.000000,Thane,Mumbai,Apartment,2,2,0,Furnished,...,19.256411,72.990150,1.633793e+07,2.862073e+06,17.517969,16337.926987,2862.073013,1,0.267982,False
8,38000000,1260,30158.730159,Andheri,Mumbai,Apartment,3,3,0,Furnished,...,19.116863,72.869980,3.232582e+07,5.674181e+06,17.553092,25655.412064,4503.318095,1,0.251760,False
9,30000000,1000,30000.000000,Andheri,Mumbai,Apartment,2,2,0,Furnished,...,19.139105,72.808266,3.024767e+07,-2.476724e+05,-0.818815,30247.672415,-247.672415,1,0.232494,False

In [31]:
ppsf_results = search_properties(
    search_df,
    min_ppsf=5_000,
    max_ppsf=15_000
)

print("PRICE PER SQ.FT SEARCH")
print("=" * 70)

print(
    "₹5,000 - ₹15,000 per sq.ft."
)

print()
print(
    "Matching Properties:",
    len(ppsf_results)
)

display(
    ppsf_results.head(15)
)

PRICE PER SQ.FT SEARCH
======================================================================
₹5,000 - ₹15,000 per sq.ft.

Matching Properties: 21351

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,latitude,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly
0,6600283,757,8719.000000,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.244410,73.123253,5.749573e+06,850709.560696,14.796047,7595.209299,1123.790701,1,0.261409,False
1,6169841,652,9462.946319,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,6.422073e+06,-252232.149199,-3.927581,9849.805444,-386.859125,1,0.257219,False
2,4599936,396,11616.000000,Dombivali,Mumbai,Apartment,1,1,0,Unfurnished,...,19.209026,73.081276,4.378319e+06,221617.430083,5.061702,11056.360025,559.639975,1,0.242774,False
3,3915000,435,9000.000000,Nala Sopara,Mumbai,Apartment,1,1,0,Unfurnished,...,19.420601,72.809319,3.663747e+06,251253.479869,6.857829,8422.405793,577.594207,1,0.208075,False
4,4900320,720,6806.000000,Ulwe,Mumbai,Apartment,1,1,0,Unfurnished,...,18.967562,73.024956,4.995038e+06,-94717.520696,-1.896232,6937.552112,-131.552112,1,0.235139,False
5,3000000,590,5084.745763,Nallasopara W,Mumbai,Apartment,1,1,0,Unfurnished,...,19.417505,72.817940,3.267132e+06,-267132.484513,-8.176359,5537.512686,-452.766923,1,0.202036,False
6,19000000,1685,11275.964392,Ulwe,Mumbai,Apartment,3,3,0,Unfurnished,...,18.971428,73.014153,1.885900e+07,141000.000000,0.747654,11192.284866,83.679525,1,0.190474,False
7,4350192,484,8988.000000,Kalyan,Mumbai,Apartment,1,1,0,Unfurnished,...,19.244410,73.123253,4.353391e+06,-3199.190115,-0.073487,8994.609897,-6.609897,1,0.239088,False
8,7564352,801,9443.635456,Kalyan,Mumbai,Apartment,2,2,0,Unfurnished,...,19.257294,73.148872,7.183914e+06,380438.243445,5.295696,8968.681344,474.954112,1,0.256649,False
9,4799800,412,11650.000000,Dombivali,Mumbai,Apartment,1,1,0,Unfurnished,...,19.209026,73.081276,4.704836e+06,94963.873022,2.018431,11419.505163,230.494837,1,0.243689,False
10,3510000,390,9000.000000,Nala Sopara,Mumbai,Apartment,1,1,0,Unfurnished,...,19.420601,72.809319,3.623268e+06,-113267.899961,-3.126125,9290.430513,-290.430513,1,0.203105,False
11,7600395,1095,6941.000000,Ulwe,Mumbai,Apartment,2,2,0,Unfurnished,...,18.967562,73.024956,8.113010e+06,-512614.840278,-6.318430,7409.141407,-468.141407,1,0.251978,False
12,2800000,484,5785.123967,Dombivli,Mumbai,Apartment,1,1,0,Unfurnished,...,19.225166,73.079681,3.119186e+06,-319186.417655,-10.233002,6444.600036,-659.476070,1,0.208572,False
13,2800000,480,5833.333333,Taloje,Mumbai,Apartment,1,1,0,Unfurnished,...,19.074299,73.116592,2.915133e+06,-115133.246315,-3.949502,6073.194263,-239.860930,1,0.213839,False
14,4500000,750,6000.000000,Shil Phata,Mumbai,Apartment,1,1,0,Unfurnished,...,19.145411,73.039452,4.696311e+06,-196311.160000,-4.180114,6261.748213,-261.748213,1,0.217648,False

In [32]:
## 💰 Deal Status Classification

We classify properties based on the difference between actual listed/observed price and predicted market price.

### Categories:

- Attractive Deal → 15% or more below predicted value
- Reasonable Deal → 5% to 15% below predicted value
- Close to Market Value → within approximately ±5%
- Slightly Expensive → 5% to 15% above predicted value
- Expensive Deal → more than 15% above predicted value

SyntaxError: invalid character '→' (U+2192) (1988873931.py, line 7)

In [33]:
def calculate_deal_status(row):

    if "price_difference_percent" not in row.index:

        return "Not Available"

    difference = row["price_difference_percent"]

    if pd.isna(difference):

        return "Not Available"

    if difference <= -15:

        return "Attractive Deal"

    elif difference <= -5:

        return "Reasonable Deal"

    elif difference < 5:

        return "Close to Market Value"

    elif difference < 15:

        return "Slightly Expensive"

    else:

        return "Expensive Deal"


search_df["deal_status"] = search_df.apply(
    calculate_deal_status,
    axis=1
)

print("Deal status classification completed.")

display(
    search_df[
        [
            "price",
            "predicted_price",
            "price_difference_percent",
            "deal_status"
        ]
    ].head(10)
)

Deal status classification completed.

      price  predicted_price  price_difference_percent            deal_status
0   6600283     5.749573e+06                 14.796047     Slightly Expensive
1   6169841     6.422073e+06                 -3.927581  Close to Market Value
2   4599936     4.378319e+06                  5.061702     Slightly Expensive
3  51980000     5.084753e+07                  2.227190  Close to Market Value
4   3915000     3.663747e+06                  6.857829     Slightly Expensive
5   4900320     4.995038e+06                 -1.896232  Close to Market Value
6  14000000     1.542673e+07                 -9.248425        Reasonable Deal
7  16400255     1.715704e+07                 -4.410956  Close to Market Value
8  74998440     6.986062e+07                  7.354382     Slightly Expensive
9  65900000     6.111737e+07                  7.825328     Slightly Expensive

In [34]:
deal_categories = [
    "Attractive Deal",
    "Reasonable Deal",
    "Close to Market Value",
    "Slightly Expensive",
    "Expensive Deal"
]

print("Available Deal Categories:")

for category in deal_categories:
    print("-", category)

Available Deal Categories:
- Attractive Deal
- Reasonable Deal
- Close to Market Value
- Slightly Expensive
- Expensive Deal

In [35]:
attractive_results = search_properties(
    search_df,
    deal_status="Attractive Deal"
)

print("ATTRACTIVE DEALS")
print("=" * 70)

print(
    "Matching Properties:",
    len(attractive_results)
)

display(
    attractive_results.head(20)
)

ATTRACTIVE DEALS
======================================================================
Matching Properties: 4363

,price,area,price_per_sqft,locality,city,property_type,bedroom_num,bathroom_num,balcony_num,furnished,...,longitude,predicted_price,price_difference,price_difference_percent,predicted_price_per_sqft,price_per_sqft_difference,anomaly_label,anomaly_score,is_anomaly,deal_status
0,2300000,500,4600.000000,Nalasopara,Mumbai,Apartment,1,1,0,Unfurnished,...,72.784462,3.191877e+06,-8.918772e+05,-27.942089,6383.754321,-1783.754321,1,0.163600,False,Attractive Deal
1,1800000,550,3272.727273,Shil Phata,Mumbai,Apartment,1,1,0,Semi-Furnished,...,73.039452,3.718367e+06,-1.918367e+06,-51.591659,6760.668057,-3487.940784,1,0.217592,False,Attractive Deal
2,26000000,1020,25490.196078,Prabhadevi,Mumbai,Apartment,2,2,0,Semi-Furnished,...,72.829720,3.264734e+07,-6.647336e+06,-20.361036,32007.191877,-6516.995799,1,0.271726,False,Attractive Deal
3,18500000,1000,18500.000000,Chembur,Mumbai,Apartment,2,2,0,Unfurnished,...,72.896896,2.248268e+07,-3.982685e+06,-17.714454,22482.684942,-3982.684942,1,0.288215,False,Attractive Deal
4,7300000,850,8588.235294,Mira Road,Mumbai,Apartment,2,2,0,Unfurnished,...,72.869827,9.185792e+06,-1.885792e+06,-20.529441,10806.813716,-2218.578422,1,0.255070,False,Attractive Deal
5,3600000,657,5479.452055,Kharghar,Mumbai,Apartment,1,2,0,Semi-Furnished,...,73.081520,4.642370e+06,-1.042370e+06,-22.453401,7066.012107,-1586.560052,1,0.187171,False,Attractive Deal
6,12500000,1500,8333.333333,Kharghar,Mumbai,Apartment,3,3,0,Unfurnished,...,73.057495,1.527245e+07,-2.772453e+06,-18.153293,10181.635461,-1848.302127,1,0.231043,False,Attractive Deal
7,11600000,880,13181.818182,Bhandup,Mumbai,Apartment,2,2,0,Unfurnished,...,72.933838,1.365350e+07,-2.053505e+06,-15.040129,15515.346254,-2333.528073,1,0.289863,False,Attractive Deal
8,59900000,1731,34604.274986,Bandra,Mumbai,Apartment,3,3,0,Semi-Furnished,...,72.829353,7.108664e+07,-1.118664e+07,-15.736628,41066.805315,-6462.530329,1,0.217375,False,Attractive Deal
9,16000000,1400,11428.571429,Thane,Mumbai,Apartment,3,3,0,Unfurnished,...,72.993095,1.893734e+07,-2.937344e+06,-15.510854,13526.674118,-2098.102689,1,0.245965,False,Attractive Deal
10,4987500,895,5572.625698,Vasai,Mumbai,Apartment,2,1,0,Semi-Furnished,...,72.875618,5.968734e+06,-9.812338e+05,-16.439564,6668.976298,-1096.350599,1,0.198954,False,Attractive Deal
11,11500000,890,12921.348315,Dahisar,Mumbai,Apartment,2,2,0,Semi-Furnished,...,72.867935,1.359109e+07,-2.091087e+06,-15.385722,15270.884081,-2349.535767,1,0.286840,False,Attractive Deal
12,3800000,710,5352.112676,Ulwe,Mumbai,Apartment,1,2,0,Unfurnished,...,73.028862,5.445990e+06,-1.645990e+06,-30.223896,7670.409119,-2318.296443,1,0.242070,False,Attractive Deal
13,2900000,490,5918.367347,Goregaon,Mumbai,Apartment,1,1,0,Unfurnished,...,72.887466,4.186431e+06,-1.286431e+06,-30.728591,8543.737449,-2625.370102,1,0.144855,False,Attractive Deal
14,7500000,440,17045.454545,Malad,Mumbai,Apartment,1,2,0,Unfurnished,...,72.850510,9.212483e+06,-1.712483e+06,-18.588720,20937.460535,-3892.005990,1,0.263401,False,Attractive Deal
15,15500000,950,16315.789474,Malad,Mumbai,Apartment,2,2,0,Unfurnished,...,72.837654,1.837952e+07,-2.879520e+06,-15.667004,19346.863318,-3031.073844,1,0.288132,False,Attractive Deal
16,3250000,1000,3250.000000,Taloja,Mumbai,Apartment,1,1,0,Unfurnished,...,73.097656,4.536503e+06,-1.286503e+06,-28.358908,4536.502600,-1286.502600,1,0.192182,False,Attractive Deal
17,2500000,455,5494.505495,Dombivali,Mumbai,Apartment,1,1,0,Unfurnished,...,73.093430,3.003324e+06,-5.033235e+05,-16.758884,6600.710998,-1106.205504,1,0.197575,False,Attractive Deal
18,17500000,700,25000.000000,Mahim,Mumbai,Apartment,1,2,0,Unfurnished,...,72.840500,2.225200e+07,-4.752005e+06,-21.355401,31788.578252,-6788.578252,1,0.257708,False,Attractive Deal
19,6900000,585,11794.871795,Kurla,Mumbai,Apartment,1,2,0,Semi-Furnished,...,72.881660,9.386490e+06,-2.486490e+06,-26.490096,16045.282576,-4250.410781,1,0.268176,False,Attractive Deal

In [36]:
normal_properties = search_properties(
    search_df,
    anomaly_status="Normal"
)

anomaly_properties = search_properties(
    search_df,
    anomaly_status="Anomaly"
)

print("ANOMALY SEARCH")
print("=" * 70)

print(
    "Normal Properties:",
    len(normal_properties)
)

print(
    "Anomalous Properties:",
    len(anomaly_properties)
)

ANOMALY SEARCH
======================================================================
Normal Properties: 51249
Anomalous Properties: 518

In [37]:
# ⭐ Property Ranking

After filtering properties, we can rank them based on:

1. Lower price per sq.ft.
2. Lower price compared with predicted market value
3. Higher area
4. Lower anomaly risk

SyntaxError: invalid syntax (4251935889.py, line 3)

In [38]:
ranking_df = search_df.copy()

ranking_df["value_score"] = 0.0

# Lower price per sq.ft. gets better score
ppsf_rank = ranking_df["price_per_sqft"].rank(
    ascending=True,
    pct=True
)

# Lower price difference gets better score
if "price_difference_percent" in ranking_df.columns:

    difference_rank = ranking_df[
        "price_difference_percent"
    ].rank(
        ascending=True,
        pct=True
    )

else:

    difference_rank = 0.5

# Higher area gets better score
area_rank = ranking_df["area"].rank(
    ascending=False,
    pct=True
)

ranking_df["value_score"] = (
    (1 - ppsf_rank) * 0.40
    +
    (1 - difference_rank) * 0.40
    +
    area_rank * 0.20
)

ranking_df = ranking_df.sort_values(
    "value_score",
    ascending=False
).reset_index(
    drop=True
)

print("Property ranking completed.")

display(
    ranking_df[
        [
            "locality",
            "price",
            "area",
            "price_per_sqft",
            "value_score"
        ]
    ].head(20)
)
ranking_df = search_df.copy()

ranking_df["value_score"] = 0.0

# Lower price per sq.ft. gets better score
ppsf_rank = ranking_df["price_per_sqft"].rank(
    ascending=True,
    pct=True
)

# Lower price difference gets better score
if "price_difference_percent" in ranking_df.columns:

    difference_rank = ranking_df[
        "price_difference_percent"
    ].rank(
        ascending=True,
        pct=True
    )

else:

    difference_rank = 0.5

# Higher area gets better score
area_rank = ranking_df["area"].rank(
    ascending=False,
    pct=True
)

ranking_df["value_score"] = (
    (1 - ppsf_rank) * 0.40
    +
    (1 - difference_rank) * 0.40
    +
    area_rank * 0.20
)

ranking_df = ranking_df.sort_values(
    "value_score",
    ascending=False
).reset_index(
    drop=True
)

print("Property ranking completed.")

display(
    ranking_df[
        [
            "locality",
            "price",
            "area",
            "price_per_sqft",
            "value_score"
        ]
    ].head(20)
)

Property ranking completed.

               locality    price  area  price_per_sqft  value_score
0            Thane Diva   700000   270     2592.592593     0.997779
1            Nalasopara   800000   303     2640.264026     0.996679
2             Ghatkopar   850000   322     2639.751553     0.996040
3               Versova   766600   349     2196.561605     0.995138
4               Versova   788800   349     2260.171920     0.995084
5                 Virar   700000   240     2916.666667     0.993776
6                 Virar   650000   250     2600.000000     0.993708
7                Kalyan   800000   250     3200.000000     0.991935
8            Nalasopara   850000   360     2361.111111     0.991616
9               Naigaon   700000   200     3500.000000     0.991097
10             Bhiwandi  1034130   385     2686.051948     0.990189
11  Rabale Station Road  1000000   300     3333.333333     0.990073
12                Virar   780000   360     2166.666667     0.989661
13               Mumbra   450000   400     1125.000000     0.989470
14                Virar   900000   350     2571.428571     0.988670
15             Bhiwandi   900000   400     2250.000000     0.987434
16              Titwala   700000   180     3888.888889     0.987013
17               Khardi   800000   275     2909.090909     0.986148
18            Dombivali   990000   400     2475.000000     0.985668
19             Dombivli   900000   360     2500.000000     0.985354

Property ranking completed.

               locality    price  area  price_per_sqft  value_score
0            Thane Diva   700000   270     2592.592593     0.997779
1            Nalasopara   800000   303     2640.264026     0.996679
2             Ghatkopar   850000   322     2639.751553     0.996040
3               Versova   766600   349     2196.561605     0.995138
4               Versova   788800   349     2260.171920     0.995084
5                 Virar   700000   240     2916.666667     0.993776
6                 Virar   650000   250     2600.000000     0.993708
7                Kalyan   800000   250     3200.000000     0.991935
8            Nalasopara   850000   360     2361.111111     0.991616
9               Naigaon   700000   200     3500.000000     0.991097
10             Bhiwandi  1034130   385     2686.051948     0.990189
11  Rabale Station Road  1000000   300     3333.333333     0.990073
12                Virar   780000   360     2166.666667     0.989661
13               Mumbra   450000   400     1125.000000     0.989470
14                Virar   900000   350     2571.428571     0.988670
15             Bhiwandi   900000   400     2250.000000     0.987434
16              Titwala   700000   180     3888.888889     0.987013
17               Khardi   800000   275     2909.090909     0.986148
18            Dombivali   990000   400     2475.000000     0.985668
19             Dombivli   900000   360     2500.000000     0.985354

In [39]:
best_properties = ranking_df.head(
    20
).copy()

print("🏆 TOP 20 VALUE-RANKED PROPERTIES")
print("=" * 80)

display(
    best_properties[
        [
            "locality",
            "price",
            "area",
            "bedroom_num",
            "bathroom_num",
            "price_per_sqft",
            "predicted_price",
            "value_score"
        ]
    ]
)

🏆 TOP 20 VALUE-RANKED PROPERTIES
================================================================================

,locality,price,area,bedroom_num,bathroom_num,price_per_sqft,predicted_price,value_score
0,Thane Diva,700000,270,1,1,2592.592593,2.227475e+06,0.997779
1,Nalasopara,800000,303,1,1,2640.264026,2.378466e+06,0.996679
2,Ghatkopar,850000,322,1,2,2639.751553,4.301451e+06,0.996040
3,Versova,766600,349,1,1,2196.561605,3.634556e+06,0.995138
4,Versova,788800,349,1,1,2260.171920,3.634556e+06,0.995084
5,Virar,700000,240,1,1,2916.666667,1.118393e+06,0.993776
6,Virar,650000,250,1,1,2600.000000,1.010546e+06,0.993708
7,Kalyan,800000,250,1,1,3200.000000,1.255938e+06,0.991935
8,Nalasopara,850000,360,1,1,2361.111111,1.495900e+06,0.991616
9,Naigaon,700000,200,1,1,3500.000000,1.157080e+06,0.991097
10,Bhiwandi,1034130,385,1,1,2686.051948,2.179502e+06,0.990189
11,Rabale Station Road,1000000,300,1,1,3333.333333,1.595470e+06,0.990073
12,Virar,780000,360,1,1,2166.666667,1.221099e+06,0.989661
13,Mumbra,450000,400,1,2,1125.000000,1.020673e+06,0.989470
14,Virar,900000,350,1,1,2571.428571,1.348014e+06,0.988670
15,Bhiwandi,900000,400,1,1,2250.000000,1.591545e+06,0.987434
16,Titwala,700000,180,1,1,3888.888889,1.233240e+06,0.987013
17,Khardi,800000,275,1,1,2909.090909,1.090596e+06,0.986148
18,Dombivali,990000,400,1,1,2475.000000,1.595000e+06,0.985668
19,Dombivli,900000,360,1,1,2500.000000,1.272997e+06,0.985354

In [40]:
def search_and_rank_properties(
    data,
    locality=None,
    min_price=None,
    max_price=None,
    min_area=None,
    max_area=None,
    bedrooms=None,
    bathrooms=None,
    property_type=None,
    furnished=None,
    min_ppsf=None,
    max_ppsf=None,
    deal_status=None,
    anomaly_status=None,
    top_n=20
):

    results = search_properties(
        data=data,
        locality=locality,
        min_price=min_price,
        max_price=max_price,
        min_area=min_area,
        max_area=max_area,
        bedrooms=bedrooms,
        bathrooms=bathrooms,
        property_type=property_type,
        furnished=furnished,
        min_ppsf=min_ppsf,
        max_ppsf=max_ppsf,
        deal_status=deal_status,
        anomaly_status=anomaly_status
    )

    if len(results) == 0:

        return results

    results = results.copy()

    # Value score
    ppsf_rank = results[
        "price_per_sqft"
    ].rank(
        ascending=True,
        pct=True
    )

    if "price_difference_percent" in results.columns:

        difference_rank = results[
            "price_difference_percent"
        ].rank(
            ascending=True,
            pct=True
        )

    else:

        difference_rank = pd.Series(
            0.5,
            index=results.index
        )

    area_rank = results[
        "area"
    ].rank(
        ascending=False,
        pct=True
    )

    results["value_score"] = (
        (1 - ppsf_rank) * 0.40
        +
        (1 - difference_rank) * 0.40
        +
        area_rank * 0.20
    )

    results = results.sort_values(
        "value_score",
        ascending=False
    )

    results = results.head(
        top_n
    ).reset_index(
        drop=True
    )

    return results


print("✅ Search + ranking function created!")

✅ Search + ranking function created!

In [41]:
final_results = search_and_rank_properties(
    data=search_df,
    min_price=5_000_000,
    max_price=15_000_000,
    min_area=600,
    max_area=1500,
    bedrooms=2,
    bathrooms=2,
    top_n=20
)

print("FINAL PROPERTY SEARCH")
print("=" * 80)

print(
    "Budget: ₹50L - ₹1.5Cr"
)

print(
    "Area: 600 - 1500 sq.ft."
)

print(
    "Bedrooms: 2"
)

print(
    "Bathrooms: 2"
)

print()
print(
    "Matching Properties:",
    len(final_results)
)

display(
    final_results[
        [
            "locality",
            "price",
            "area",
            "bedroom_num",
            "bathroom_num",
            "price_per_sqft",
            "predicted_price",
            "deal_status",
            "value_score"
        ]
    ]
)

FINAL PROPERTY SEARCH
================================================================================
Budget: ₹50L - ₹1.5Cr
Area: 600 - 1500 sq.ft.
Bedrooms: 2
Bathrooms: 2

Matching Properties: 20

,locality,price,area,bedroom_num,bathroom_num,price_per_sqft,predicted_price,deal_status,value_score
0,Airoli,5100000,800,2,2,6375.000000,9.062599e+06,Attractive Deal,0.908498
1,Panvel,5133600,713,2,2,7200.000000,7.335189e+06,Attractive Deal,0.898981
2,Panvel,5256000,730,2,2,7200.000000,7.427752e+06,Attractive Deal,0.894704
3,Kharghar,5500000,855,2,2,6432.748538,7.980530e+06,Attractive Deal,0.885088
4,Panvel,5500000,883,2,2,6228.765572,8.029501e+06,Attractive Deal,0.883736
5,Chembur,5500000,700,2,2,7857.142857,1.036044e+07,Attractive Deal,0.882783
6,Dombivali,5099000,826,2,2,6173.123487,6.368365e+06,Attractive Deal,0.882750
7,Nerul,5500000,700,2,2,7857.142857,9.078710e+06,Attractive Deal,0.881099
8,Thane,5500000,900,2,2,6111.111111,8.054353e+06,Attractive Deal,0.880368
9,Vashi,5900000,845,2,2,6982.248521,9.602507e+06,Attractive Deal,0.879360
10,Panvel,5000000,780,2,2,6410.256410,6.025038e+06,Attractive Deal,0.879083
11,Vasai,5000000,750,2,2,6666.666667,6.010885e+06,Attractive Deal,0.878218
12,Panvel,5760000,800,2,2,7200.000000,8.263385e+06,Attractive Deal,0.877255
13,Kalyan,5000000,980,2,2,5102.040816,8.082522e+06,Attractive Deal,0.876291
14,Kalyan,5100000,750,2,2,6800.000000,6.137814e+06,Attractive Deal,0.875493
15,Kalyan,5000000,670,2,2,7462.686567,6.016376e+06,Attractive Deal,0.873299
16,Ulwe,6000000,800,2,2,7500.000000,1.086660e+07,Attractive Deal,0.872513
17,Panvel,5000000,850,2,2,5882.352941,5.985361e+06,Attractive Deal,0.870596
18,Panvel,5940000,825,2,2,7200.000000,8.507529e+06,Attractive Deal,0.870430
19,Panvel,5199000,921,2,2,5644.951140,6.579712e+06,Attractive Deal,0.868779

In [42]:
print("🔎 SEARCH RESULT SUMMARY")
print("=" * 70)

if len(final_results) == 0:

    print("No properties matched the selected filters.")

else:

    print(
        "Number of Results:",
        len(final_results)
    )

    print(
        f"Average Price: ₹{final_results['price'].mean():,.0f}"
    )

    print(
        f"Average Area: {final_results['area'].mean():,.0f} sq.ft."
    )

    print(
        f"Average Price/Sq.Ft.: "
        f"₹{final_results['price_per_sqft'].mean():,.0f}"
    )

    if "predicted_price" in final_results.columns:

        print(
            f"Average Predicted Price: "
            f"₹{final_results['predicted_price'].mean():,.0f}"
        )

    print()
    print("Top Localities:")

    display(
        final_results[
            "locality"
        ].value_counts().head(10)
    )

🔎 SEARCH RESULT SUMMARY
======================================================================
Number of Results: 20
Average Price: ₹5,349,380
Average Area: 804 sq.ft.
Average Price/Sq.Ft.: ₹6,714
Average Predicted Price: ₹7,788,759

Top Localities:

locality
Panvel       8
Kalyan       3
Airoli       1
Kharghar     1
Chembur      1
Dombivali    1
Nerul        1
Thane        1
Vashi        1
Vasai        1
Name: count, dtype: int64

In [43]:
search_output_path = os.path.join(
    OUTPUT_DIR,
    "property_search_results.csv"
)

final_results.to_csv(
    search_output_path,
    index=False
)

print("✅ Search results exported successfully!")

print()
print(
    "File:",
    search_output_path
)

✅ Search results exported successfully!

File: C:\Users\Tejas Dalvi\OneDrive\Documents\mumbai-house-price-prediction\outputs\property_search_results.csv

In [44]:
attractive_output_path = os.path.join(
    OUTPUT_DIR,
    "attractive_property_deals.csv"
)

attractive_results.to_csv(
    attractive_output_path,
    index=False
)

print("✅ Attractive property results exported!")

print()
print(
    "File:",
    attractive_output_path
)

✅ Attractive property results exported!

File: C:\Users\Tejas Dalvi\OneDrive\Documents\mumbai-house-price-prediction\outputs\attractive_property_deals.csv

In [45]:
search_dataset_path = os.path.join(
    OUTPUT_DIR,
    "property_search_dataset.csv"
)

search_df.to_csv(
    search_dataset_path,
    index=False
)

print("✅ Search-ready dataset exported.")

print()
print(
    search_dataset_path
)

✅ Search-ready dataset exported.

C:\Users\Tejas Dalvi\OneDrive\Documents\mumbai-house-price-prediction\outputs\property_search_dataset.csv

In [46]:
print("OUTPUT FILES")
print("=" * 70)

output_files = [
    search_output_path,
    attractive_output_path,
    search_dataset_path
]

for file_path in output_files:

    if os.path.exists(file_path):

        file_size = os.path.getsize(
            file_path
        )

        print(
            f"✅ {os.path.basename(file_path)} "
            f"({file_size / 1024:.2f} KB)"
        )

    else:

        print(
            f"❌ Missing: {file_path}"
        )

OUTPUT FILES
======================================================================
✅ property_search_results.csv (5.27 KB)
✅ attractive_property_deals.csv (1007.01 KB)
✅ property_search_dataset.csv (12091.14 KB)

In [47]:
print("🏠 PROPERTY SEARCH ENGINE DEMO")
print("=" * 80)

demo_results = search_and_rank_properties(
    data=search_df,
    min_price=7_500_000,
    max_price=20_000_000,
    min_area=700,
    max_area=1800,
    bedrooms=2,
    top_n=10
)

if len(demo_results) == 0:

    print("No matching properties found.")

else:

    display(
        demo_results[
            [
                "locality",
                "price",
                "area",
                "bedroom_num",
                "bathroom_num",
                "price_per_sqft",
                "predicted_price",
                "deal_status",
                "value_score"
            ]
        ]
    )

🏠 PROPERTY SEARCH ENGINE DEMO
================================================================================

,locality,price,area,bedroom_num,bathroom_num,price_per_sqft,predicted_price,deal_status,value_score
0,Koper Khairane,7500000,900,2,2,8333.333333,1.270841e+07,Attractive Deal,0.882470
1,Thane,7526400,896,2,2,8400.000000,1.053601e+07,Attractive Deal,0.877271
2,Ghansoli,7500000,820,2,2,9146.341463,1.225534e+07,Attractive Deal,0.875442
3,Dahisar,7600000,900,2,2,8444.444444,1.089518e+07,Attractive Deal,0.873127
4,Mira Road,7600000,980,2,2,7755.102041,1.059568e+07,Attractive Deal,0.867163
5,Thane,7954800,947,2,2,8400.000000,1.172536e+07,Attractive Deal,0.864217
6,Goregaon,7500000,800,2,2,9375.000000,9.751535e+06,Attractive Deal,0.861643
7,Mira Road,7500000,860,2,2,8720.930233,9.367579e+06,Attractive Deal,0.860434
8,Koper Khairane,8000000,950,2,2,8421.052632,1.165162e+07,Attractive Deal,0.859628
9,Goregaon,8050000,900,2,2,8944.444444,1.810572e+07,Attractive Deal,0.859421

In [48]:
print("📊 PROPERTY SEARCH ENGINE STATISTICS")
print("=" * 80)

print(
    f"Total Dataset Properties: {len(df):,}"
)

print(
    f"Searchable Properties: {len(search_df):,}"
)

print(
    f"Available Localities: {search_df['locality'].nunique():,}"
)

print(
    f"Available Property Types: "
    f"{search_df['property_type'].nunique():,}"
)

print(
    f"Attractive Deals: "
    f"{(search_df['deal_status'] == 'Attractive Deal').sum():,}"
)

print(
    f"Anomalous Properties: "
    f"{search_df['is_anomaly'].sum():,}"
)

print()
print("Search engine is ready for dashboard integration.")

📊 PROPERTY SEARCH ENGINE STATISTICS
================================================================================
Total Dataset Properties: 51,767
Searchable Properties: 51,767
Available Localities: 408
Available Property Types: 5
Attractive Deals: 4,363
Anomalous Properties: 518

Search engine is ready for dashboard integration.

In [49]:
# ✅ Notebook 14 Completed

The Property Search & Filter Engine has been successfully created.

### Implemented Features

- ✅ Locality Search
- ✅ Price Range Filter
- ✅ Area Range Filter
- ✅ Bedroom Filter
- ✅ Bathroom Filter
- ✅ Property Type Filter
- ✅ Furnishing Filter
- ✅ Price/Sq.Ft. Filter
- ✅ Deal Status Filter
- ✅ Anomaly Filter
- ✅ Multi-Filter Search
- ✅ Property Ranking
- ✅ Value Score
- ✅ Search Result Export
- ✅ Attractive Deal Export

### Generated Files

The following files are saved inside the `outputs` folder:

- `property_search_results.csv`
- `attractive_property_deals.csv`
- `property_search_dataset.csv`

### Next Step

The search engine can now be integrated into the Flask dashboard.

The next notebook will focus on:

**15. Prediction Confidence / Uncertainty Range**

This will provide a prediction range around the estimated property price instead of showing only one predicted value.

SyntaxError: invalid character '✅' (U+2705) (1113859363.py, line 7)